version: '3.8'

services:
  customers.management.webapi:
    build:
        context: .
        dockerfile: src/Customers.Management.WebApi/Dockerfile
    container_name: customer_management_webapi_container
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=Portfolio;User=sa;Password=Xpto1234;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    networks: 
      - mynetwork

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Xpto1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - mynetwork

networks: 
  mynetwork:

volumes:
  sqlserverdata: